### ISSUE TITLE
reverse sorting?

### ISSUE THREAD

**Issue by vrmerlin** [75lb/sort-array#1]
Hi -- is there any way to control whether the sorting for a property is in ascending or descending order?

**Comment by 75lb** [comment]
not at the moment.. for now, I recommend you use [lodash.orderBy](https://lodash.com/docs/4.17.4#orderBy).

**Comment by 75lb** [comment]
or you can simply `.reverse()` the output from this module.

**Comment by vrmerlin** [comment]
Ok, thank you!

**Comment by 75lb** [comment]
reverse sorting added and released in v3.0.0
