### ISSUE TITLE
add the ability to sort in a new array

### ISSUE THREAD

**Issue by chiptus** [75lb/sort-array#10]
Just found out about this library, great job! 
reading the code, the sort happens in-place. It would be nice if I could leave the original array as is, and get a new sorted array

**Comment by 75lb** [comment]
Hi, thanks!

> It would be nice if I could leave the original array as is, and get a new sorted array

Making this change default could have significant memory and performance implications. What if the user is passing in an array of 100,000,000 primative values (e.g. strings) and sort-array duplicated this array? That operation would immediately double the memory consumption of the user's app and potentially slow things down (depending on the system and how hard GC has to work to find and remove redundant memory allocations). 

Whether the array is duplicated or not is the decision of the user, not `sort-array`. If you want a new array each time then simply create one yourself. 

```js
const array = [1, 2, 3, 4, 5]
const result = sortArray(array.slice())
```
