### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by eladonline** [75lb/sort-array#11]
I needed to sort a list by string ex: all items with the property "source" 
if it equals to "Unlinked" it should drop to the end of the list 
if it doesn't equals to "Unlinked" it should be shifted to start of the array
I managed to do this like this:

```
  return sortArray(list, {
    by: "source",
    order,
    computed: {
      total: source => (source === "Unlinked" ? 1 : 0),
    },
  });  
```
I suggest you add a support for that

**Comment by 75lb** [comment]
You way you solved it (using a computed column) was the correct solution - this is how custom requirements like yours are solved.. Feel free to add an example to the [wiki](https://github.com/75lb/sort-array/wiki) if you like!

**Comment by 75lb** [comment]
Another option would be to set the `Unlinked` values to `null` or `undefined` then use the `nullRank` and/or `undefinedRank` options: 
https://github.com/75lb/sort-array#sortarrayarray-options--array-
