### ISSUE TITLE
Bugfix

### ISSUE THREAD

**Issue by HolgerSchulz** [75lb/sort-array#16]
Sorting of this failed:
```
   var ar = [[99, "a"], [1, "a"]];
   sortArray(ar, {by:[1,0]});
```

I changed this line
`if (result === 0 && by[byIndex + 1]) {`
to this
`if (result === 0 && (undefined !== by[byIndex + 1])) {`
to fix it.

**Comment by 75lb** [comment]
fixed and released in v4.1.5, thanks.. let me know if you spot anything else 👍
