### ISSUE TITLE
How are NULL values handled?

### ISSUE THREAD

**Issue by BrianT71** [75lb/sort-array#9]
I'm using sortArray with an array that contains null values in field.

sortArray(myArray, {by: ['fieldA',fieldB']})

fieldA contains two values, null and the number "1". Regardless of how I sort the array (asc or desc), the null values are always at the end. I was expecting them to be first when using asc order but they are last in both cases.

**Comment by 75lb** [comment]
see `nullRank` and `undefinedRank` in [the options](https://github.com/75lb/sort-array#sortarrayarray-options--array-)
